name: e2eTests

on:
  repository_dispatch:
    types: [run-e2e]

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: us-west-1

jobs:
  terratest:
    name: 'Terratest'
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
    steps:
      - name: CheckoutPR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::270074865685:role/terraform-module-ci-test
          role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
          aws-region: ${{env.AWS_REGION}}

      - name: Run Terratest
        run: cd ./tests && go test -v -timeout=40m -parallel=10
