name: e2eTests

on: workflow_dispatch

env:
  AWS_REGION: us-west-1

jobs:
  terratest:
    name: 'Terratest'
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::270074865685:role/terraform-module-ci-test
          role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
          aws-region: ${{env.AWS_REGION}}
      - name: Run Terratest
        run: cd ./tests && go test -v -timeout=40m -parallel=10
