name: Release

on:
  push:
    branches:
    - main

env:
  AWS_REGION: us-west-1

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module

      - name: 'Remind to wait'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.release-please.outputs.pr }}
          body: |
            Please make sure e2e tests pass before approving PR!

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::270074865685:role/terraform-module-ci-test
          role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
          aws-region: ${{env.AWS_REGION}}

      - name: 'Run Terratest'
        run: cd ./tests && go test -v -timeout=40m -parallel=10

      - name: 'Report Success'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.release-please.outputs.pr.number }}
          body: |
            End to End Tests Passed!