name: Remind

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions:
  id-token: write

jobs:
  remind-about-e2e-testing:
    name: 'Remind about e2e tests'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for your contribution!

      - uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Reviewers!
            Please make sure the e2e tests pass before approving.

      - uses: peter-evans/repository-dispatch@v2
        with:
          event-type: run-e2e
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'