name: Tests

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

jobs:
  remind-about-e2e-testing:
    name: 'Remind about e2e tests'
    runs-on: ubuntu-latest
    steps:
      - name: Comment-to-contributor
        uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          with:
            message: |
              Hi @${{ github.actor }}, thanks for your pull request!

              This module has e2e tests that run on every pull request. Please make sure to run them locally before submitting your PR.

              To run the tests, you need to have Go installed and be authenticated to AWS.
              Then, run the following commands:

              ```shell
              cd ./tests
              go test -v -timeout=40m -parallel=10
              ```
      - name: Comment-to-reviewer
        uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            All Reviewers!
            Do not approve this PR unless the e2eTests workflow has passed.
            You will need to trigger the e2eTests workflow manually by clicking the "Run workflow" button on the Actions tab.
            Please input $${{ github.event.pull_request.head.ref }} as the pull_request_head_ref input.
